<h1>ACL</h1>

<div class="tracy-inner">
	<h2>Authenticator's methods</h2>
	<table>
		<thead>
			<tr>
				<th>Methods start loginBy*</th>
			</tr>
		</thead>

		<tbody>
			<?php foreach ($authenticatorMethods as $method) { ?>
				<tr class="no"><td><?php echo $method['prototype'] ?> <?php echo \Tracy\Helpers::editorLink($method['file'], $method['line']) ?></td></tr>
			<?php } ?>
		</tbody>
	</table>

	<?php if ($authorizatorMethods === NULL): ?>
	<p>Authorizator is not enable.</p>
	<?php else: ?>
	<h2>Authorizator's methods</h2>
	<table>
		<thead>
			<tr>
				<th><?php echo Nette\Security\User::class; ?>::isAllowed()</th>
				<th>Permission resource*</th>
			</tr>
		</thead>

		<tbody>
			<?php foreach ($authorizatorMethods as $method) { ?>
			<tr class="no"><td><?php echo $method['user'] ?></td><td><?php echo $method['prototype'] ?> <?php echo \Tracy\Helpers::editorLink($method['file'], $method['line']) ?></td></tr>
					<?php } ?>
			<?php if(!$authorizatorMethods) { ?>
			<tr><td>No methods defined.</td></tr>
			<?php } ?>
		</tbody>
	</table>
	<?php endif; ?>
</div>